<a href="https://colab.research.google.com/github/omkar87796-sudo/personal-diary/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
lst=[2,3,1,5,6]
arr1=np.array(lst)

In [10]:
arr1

array([2, 3, 1, 5, 6])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1.ndim

1

In [13]:
arr1.size

5

In [14]:
arr1.shape

(5,)

In [15]:
lst2=[[1,2,3],
      [4,5,6],
      [7,8,9]]

In [16]:
arr2=np.array(lst2)

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
type(arr2)

numpy.ndarray

In [19]:
arr2.ndim

2

In [20]:
arr2.size

9

In [21]:
arr2.shape

(3, 3)

In [22]:
image=[[[1,2,3],
        [4,5,6],
        [7,8,9]],
       [[10,11,12],
        [13,14,15],
        [16,17,18]],
       [[19,20,21],
        [22,23,24],
        [25,26,27]]]

In [24]:
image = np.array(image)

In [25]:
image.ndim

3

In [26]:
image.size

27

In [27]:
image.shape

(3, 3, 3)

In [28]:
image.dtype

dtype('int64')

In [43]:
arr3 = np.arange(3,99,2).reshape(4,3,4)
arr3

array([[[ 3,  5,  7,  9],
        [11, 13, 15, 17],
        [19, 21, 23, 25]],

       [[27, 29, 31, 33],
        [35, 37, 39, 41],
        [43, 45, 47, 49]],

       [[51, 53, 55, 57],
        [59, 61, 63, 65],
        [67, 69, 71, 73]],

       [[75, 77, 79, 81],
        [83, 85, 87, 89],
        [91, 93, 95, 97]]])

In [32]:
arr3.size

48

In [50]:
arr4 = np.random.randint(1,1000)
arr4

313

In [62]:
np.random.randint(10,20,5)

array([10, 10, 18, 18, 15])

In [64]:
np.linspace(11,25,18).reshape(3,3,2)

array([[[11.        , 11.82352941],
        [12.64705882, 13.47058824],
        [14.29411765, 15.11764706]],

       [[15.94117647, 16.76470588],
        [17.58823529, 18.41176471],
        [19.23529412, 20.05882353]],

       [[20.88235294, 21.70588235],
        [22.52941176, 23.35294118],
        [24.17647059, 25.        ]]])

In [66]:
arr6 =np.arange(2,10,1).reshape(4,2)
arr7 =np.arange(12,20,1).reshape(4,2)

In [68]:
arr6

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [67]:
arr6*2

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [70]:
arr6+7

array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [72]:
arr6%7

array([[2, 3],
       [4, 5],
       [6, 0],
       [1, 2]])

In [77]:
arr6

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [76]:
arr6.sum(axis=1)

array([ 5,  9, 13, 17])

In [78]:
arr6.sum(axis=0)

array([20, 24])